hive-node: https://api.hive.blog
accounts:
  - name: ACCOUNT_1
    posting-key: POSTING_KEY
    actions:
      - stake
      - claim-hive-sps-airdrop
  - name: ACCOUNT_2
    posting-key: POSTING_KEY
    actions:
      - claim-hive-sps-airdrop